### ISSUE TITLE
puntos pendientes

### ISSUE THREAD

**Issue by imadueno** [lmorillo96/Interactive-CARD#2]
- capturar expiración de tarjeta
- capturar código verificación tarjeta
- acomodar la tarjeta con vista posterior usando CSS

**Comment by lmorillo96** [comment]
DONE!

**Comment by lmorillo96** [comment]
![image](https://user-images.githubusercontent.com/66586644/197678421-30e7586d-7928-4cb0-ba30-d535f960bba3.png)

**Comment by imadueno** [comment]
Excelente, damos por cerrado el issue.
