### ISSUE TITLE
input form validations just html

### ISSUE THREAD

**Issue by imadueno** [lmorillo96/Interactive-CARD#3]
Hay que agregar validaciones y cambios a los inputs.

- Los inputs que acepten números cambiar a type="number"
- agregar el attributo "pattern" y "title" para agregar una validación y la descripción del error
- verificar que cuando se capture un nombre muy largo no afecte el diseño de la tarjeta, hay que ocultar el texto excedente. 

![image](https://user-images.githubusercontent.com/29583359/197679330-061a72b9-1646-4b51-b280-f39b7f0ecc28.png)

**Comment by lmorillo96** [comment]
![image](https://user-images.githubusercontent.com/66586644/199149695-1b4e939b-2142-43cc-a03d-530a468e8fbb.png)

Get it!

Se generó la validación de texto mediante atributos HTML!

**Comment by imadueno** [comment]
Conseguido, validaciones con atributos HTML 👍
